@echo off
echo Starting Laravel Development Server...
start "Laravel Artisan" cmd /k "php83 artisan serve"
echo Starting Reverb Server...
start "Laravel Reverb" cmd /k "php83 artisan reverb:start"
echo Starting Vite Asset Server...
start "Vite" cmd /k "npm run dev"
echo Servers started in background windows.
